name: Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment to Render
        run: curl --fail --show-error -X POST ${{ secrets.RENDER_PROD_DEPLOY_HOOK }}